Task3
echekholskiy/Task3 pull request #1
Opened 2021-06-10 06:28 UTC by echekholskiy

2021-06-10 15:18 UTC, asushkov-github requested changes

2021-06-10 15:18 UTC, asushkov-github commented on VKApp/Extensions/AuthorizePageExtensions.cs
> +        public static void OpenAuthorizePageInNewWindowAndSwitch(this AuthorizePage authorizePage)
Why do you need extension, if you don't use authorizePage variable? Let's move it to AutenticationUtils class

2021-06-10 15:18 UTC, asushkov-github commented on VKApp/Pages/MainPage.cs
> +            return new TextField(By.XPath($"//div[@id='wpt{ownerId}" + "_" + $"{postId}']")).Displayed;
You don't need '+' in interpolation

2021-06-10 15:18 UTC, asushkov-github commented on VKApp/Utils/ApiClient.cs
> +        private const int Timeout = 2;
TimeoutInSeconds

2021-06-10 15:18 UTC, asushkov-github commented on VKApp/Utils/ApiClient.cs
> +            _token = GetToken();
`_token = AuthenticationUtils.GetToken()`

2021-06-10 15:18 UTC, asushkov-github commented on VKApp/Utils/ApiClient.cs
> +                File.ReadAllBytes(FileManager.GetImagePath()),
`FileManager.GetImagePath().GetBytes()`

2021-06-10 15:18 UTC, asushkov-github commented on VKApp/Utils/ApiClient.cs
> +                Path.GetFileName(Configuration.PictureName),
`Configuration.PictureName.GetFileName()`

2021-06-10 15:18 UTC, asushkov-github commented on VKApp/Utils/ApiClient.cs
> +    public class ApiClient
I would suggest you to split this class on ApiClient base abstract class and VkApiClient implementation.

2021-06-11 07:53 UTC, echekholskiy commented on Task3/Test/Hooks.cs
> +            Activator.CreateInstance<MainPage>();
hmm, done

2021-06-11 07:57 UTC, echekholskiy commented on Task3/Test/TestContext.cs
> +                .BeTrue("LoginPage is not opened");
done

2021-06-11 07:58 UTC, echekholskiy commented on Task3/Test/TestContext.cs
> +            _messageText = Faker.Country.Name();
done by Faker.Lorem.Paragraph(), ok?

2021-06-11 08:13 UTC, echekholskiy commented on Task3/Test/TestContext.cs
> +            TestSite.MainPage.PostIsDeleted(OwnerId, _postId);
done

2021-06-11 08:20 UTC, echekholskiy commented on VKApp/Extensions/ApiClientExtensions.cs
> +            return "photo" + savePhoto.Response[0].OwnerId + "_" + savePhoto.Response[0].Id;
done

2021-06-11 08:34 UTC, echekholskiy commented on VKApp/Pages/MainPage.cs
> +            return new TextField(By.XPath($"//div[@id='wpt{ownerId}" + "_" + $"{postId}']")).Displayed;
done

2021-06-11 08:34 UTC, echekholskiy commented on VKApp/Utils/ApiClient.cs
> +        private const int Timeout = 2;
done

2021-06-11 08:42 UTC, echekholskiy commented on VKApp/Utils/ApiClient.cs
> +                File.ReadAllBytes(FileManager.GetImagePath()),
by Extension? Or create GetImage method in FileManager?

2021-06-11 08:44 UTC, echekholskiy commented on Task3/Test/Hooks.cs
> +            ImageManager.DeleteTestImage();
It's dowloaded test image.

2021-06-11 10:15 UTC, echekholskiy commented on VKApp/Utils/ApiClient.cs
> +            _token = GetToken();
done

2021-06-11 10:18 UTC, echekholskiy commented on VKApp/Extensions/AuthorizePageExtensions.cs
> +        public static void OpenAuthorizePageInNewWindowAndSwitch(this AuthorizePage authorizePage)
done

2021-06-11 10:33 UTC, echekholskiy commented on Task3/Test/Test.cs
> +            WhenCreatedPostByApi();
done

2021-06-11 10:34 UTC, echekholskiy commented on Task3/Test/TestContext.cs
> +            _messageText = Faker.Company.CatchPhrase();
-//-

2021-06-11 11:52 UTC, echekholskiy commented on VKApp/Utils/ApiClient.cs
> +    public class ApiClient
done

2021-06-11 14:09 UTC, echekholskiy commented on Task3/Resources/appsettings.json
> +  "AuthenticationUrl": "https://oauth.vk.com/authorize?client_id=7869182&scope=204804&redirect_uri=https://oauth.vk.com/blank.html&display=page&response_type=token&revoke=1"
done

2021-06-11 14:58 UTC, echekholskiy commented on Task3/Test/TestContext.cs
> +            _messageText = Faker.Country.Name();
done

2021-06-11 14:59 UTC, echekholskiy commented on Task3/Test/TestContext.cs
> +            _messageText = Faker.Company.CatchPhrase();
done

2021-06-12 06:50 UTC, echekholskiy commented on VKApp/Utils/ApiClient.cs
> +                File.ReadAllBytes(FileManager.GetImagePath()),
done

2021-06-12 06:54 UTC, echekholskiy commented on VKApp/Utils/ApiClient.cs
> +                Path.GetFileName(Configuration.PictureName),
done

2021-06-12 07:39 UTC, echekholskiy commented on Task3/Test/TestContext.cs
> +            ImageManager.DownloadImageByUrl(imageUrl, Configuration.TestPictureName);
done

2021-06-12 07:39 UTC, echekholskiy commented on Task3/Test/Hooks.cs
> +            ImageManager.DeleteTestImage();
done

2021-06-12 07:39 UTC, closed without merging